approvedGitRepositories:
  - "https://github.com/foundry-rs/forge-std.git"

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmRegistryServer: "https://registry.npmjs.org"

preferReuse: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.16.0.cjs
