[setting.deployer]

[invoke.permitCreatePool]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = [
    "<%= formatBytes32String('createPool') %>",
    "<%= settings.sc_pool_owner %>",
]
depends=["provision.system"]
