module.exports = {
  ...require('./approveCollateral'),
  ...require('./borrowUsd'),
  ...require('./createAccount'),
  ...require('./delegateCollateral'),
  ...require('./depositCollateral'),
  ...require('./getCollateralBalance'),
  ...require('./getCollateralConfig'),
  ...require('./setSnxBalance'),
  ...require('./importCoreProxy'),
  ...require('./importSnx'),
  ...require('./setConfig'),
  ...require('./setEthBalance'),
  ...require('./withdrawCollateral'),
  ...require('./wrapEth'),
};
