[setting.chainlinkCcipRouter]

[setting.chainlinkCcipTokenPool]

[setting.chainlinkFunctions]

[setting.syncPoolCode]

[invoke.configureChainlinkCrossChain]
target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "configureChainlinkCrossChain"
args = [
    "<%= settings.chainlinkCcipRouter %>",
    "<%= settings.chainlinkCcipTokenPool %>",
    "<%= settings.chainlinkFunctions %>",
]

depends=["provision.system"]

[invoke.setSyncPoolChainlinkFunctionCode]

target = ["system.CoreProxy"]
fromCall.func = "owner"
func = "setConfig"
args = [
    "<%= formatBytes32String('performUpkeep_syncPool') %>",
    "<%= defaultAbiCoder.encode(['address'], [settings.syncPoolCode]) %>",
]

depends=["provision.system"]
