include = [
    "./eth.toml"
]

[setting.weth_address]

[invoke.setSynthMaxMarketCollateralEth]
target = ["system.CoreProxy"]
fromCall.func = "owner"
fromCall.args = []

func = "configureMaximumMarketCollateral"
args = [
  "<%= extras.synth_eth_market_id %>", 
  "<%= settings.weth_address %>",
  "<%= parseEther(settings.synthEthMaxMarketCollateral) %>"
]

depends = ["invoke.createEthSynth"]

[invoke.configureSynthWrapperEth]
target = ["spotFactory.SpotMarketProxy"]
fromCall.func = "getMarketOwner"
fromCall.args = ["<%= extras.synth_eth_market_id %>"]

func = "setWrapper"
args = [
  "<%= extras.synth_eth_market_id %>", 
  "<%= settings.weth_address %>",
  "<%= parseEther(settings.synthEthMaxMarketCollateral) %>"
]

depends = ["invoke.createEthSynth"]